const createGameBoard = () => {
    const gameBoard = {
        A: [
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: true },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
        ],
        B: [
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: true },
        ],
        C: [
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
        ],
        D: [
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: false },
        ],
        E: [
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: false },
        ],
        F: [
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: false },
        ],
        G: [
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: false },
        ],
        H: [
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: true },
        ],
        I: [
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: true },
            { hit: false, ship: true },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
        ],
        J: [
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
            { hit: false, ship: false },
        ],
    }

    const sinkAllShips = () => {
        const [columns, data] = Object.entries(gameBoard)

        columns[data].forEach(column => {
            if(column.ship === true) column.hit = true;
        })
    }

    const receiveAttack = (column, row) => {
        gameBoard.column[row].hit = true
    }
}
